CC = gcc
CFLAGS = -Wall -Wextra -std=c11

SRC = system_expert.c main.c
OBJ = $(SRC:.c=.o)

TARGET = SystemExpert

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c system_expert.h
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJ) $(TARGET)
