CC = gcc
CFLAGS = -Wall -Wextra -std=c99
SRC = system_expert.c main.c
OBJ = $(SRC:.c=.o)
EXEC = projet_system_expert

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(EXEC)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXEC)